"""
Curiosity Engine - Identification and prioritization of knowledge gaps.

The Curiosity Engine identifies knowledge gaps, prioritizes them based on
potential impact, and drives the system to explore and learn about them.
"""

import json
import logging
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class GapType(Enum):
    """Enumeration of knowledge gap types."""
    MISSING_CONCEPT = "missing_concept"
    INCOMPLETE_RELATIONSHIP = "incomplete_relationship"
    UNEXPLAINED_PHENOMENON = "unexplained_phenomenon"
    CONFLICTING_INFORMATION = "conflicting_information"
    UNTESTED_HYPOTHESIS = "untested_hypothesis"
    EDGE_CASE = "edge_case"


class GapPriority(Enum):
    """Enumeration of gap priorities."""
    LOW = 0.3
    MEDIUM = 0.6
    HIGH = 0.8
    CRITICAL = 0.95


@dataclass
class KnowledgeGap:
    """
    Represents an identified knowledge gap.
    """
    gap_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    gap_type: str = GapType.MISSING_CONCEPT.value
    
    # Gap Description
    description: str = ""
    context: Dict[str, Any] = field(default_factory=dict)
    
    # Impact Assessment
    potential_impact: float = 0.5  # 0.0 to 1.0
    priority: float = 0.5  # 0.0 to 1.0
    urgency: float = 0.5  # 0.0 to 1.0
    
    # Related Information
    related_concepts: List[str] = field(default_factory=list)
    related_questions: List[str] = field(default_factory=list)
    
    # Investigation
    investigation_status: str = "identified"  # identified, investigating, resolved
    investigation_methods: List[str] = field(default_factory=list)
    
    # Resolution
    proposed_solutions: List[str] = field(default_factory=list)
    resolution_evidence: List[Dict[str, Any]] = field(default_factory=list)
    
    # Timeline
    identified_at: datetime = field(default_factory=datetime.utcnow)
    investigation_started: Optional[datetime] = None
    resolved_at: Optional[datetime] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        data = asdict(self)
        data['identified_at'] = self.identified_at.isoformat()
        if data['investigation_started']:
            data['investigation_started'] = self.investigation_started.isoformat()
        if data['resolved_at']:
            data['resolved_at'] = self.resolved_at.isoformat()
        return data


@dataclass
class CuriosityQuery:
    """
    Represents a curiosity-driven query generated by the system.
    """
    query_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    gap_id: str = ""
    
    # Query Details
    question: str = ""
    search_keywords: List[str] = field(default_factory=list)
    
    # Exploration
    exploration_depth: int = 1
    max_depth: int = 5
    
    # Results
    results: List[Dict[str, Any]] = field(default_factory=list)
    insights_gained: List[str] = field(default_factory=list)
    
    # Timeline
    created_at: datetime = field(default_factory=datetime.utcnow)
    executed_at: Optional[datetime] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        data = asdict(self)
        data['created_at'] = self.created_at.isoformat()
        if data['executed_at']:
            data['executed_at'] = self.executed_at.isoformat()
        return data


class CuriosityEngine:
    """
    Identifies and prioritizes knowledge gaps to drive learning.
    
    The Curiosity Engine enables the system to identify what it doesn't know,
    prioritize learning opportunities, and actively explore knowledge gaps.
    """
    
    def __init__(self):
        """Initialize the Curiosity Engine."""
        self.gaps: Dict[str, KnowledgeGap] = {}
        self.gaps_by_type: Dict[str, List[str]] = {}  # type -> [gap_ids]
        self.gaps_by_concept: Dict[str, List[str]] = {}  # concept_id -> [gap_ids]
        self.queries: Dict[str, CuriosityQuery] = {}
        self.logger = logging.getLogger(__name__)
    
    def identify_gap(self, gap_type: str, description: str,
                    potential_impact: float = 0.5, urgency: float = 0.5) -> KnowledgeGap:
        """
        Identify a new knowledge gap.
        
        Args:
            gap_type: Type of knowledge gap
            description: Description of the gap
            potential_impact: Potential impact of filling the gap
            urgency: Urgency of addressing the gap
            
        Returns:
            The identified KnowledgeGap
        """
        gap = KnowledgeGap(
            gap_type=gap_type,
            description=description,
            potential_impact=potential_impact,
            urgency=urgency
        )
        
        # Calculate priority
        gap.priority = (potential_impact * 0.6 + urgency * 0.4)
        
        self.gaps[gap.gap_id] = gap
        
        # Index by type
        if gap_type not in self.gaps_by_type:
            self.gaps_by_type[gap_type] = []
        self.gaps_by_type[gap_type].append(gap.gap_id)
        
        self.logger.info(f"Identified knowledge gap {gap.gap_id}: {description}")
        return gap
    
    def get_gap(self, gap_id: str) -> Optional[KnowledgeGap]:
        """
        Retrieve a knowledge gap by ID.
        
        Args:
            gap_id: The ID of the gap
            
        Returns:
            The KnowledgeGap, or None if not found
        """
        return self.gaps.get(gap_id)
    
    def get_gaps_by_type(self, gap_type: str) -> List[KnowledgeGap]:
        """
        Get all gaps of a specific type.
        
        Args:
            gap_type: The type of gaps
            
        Returns:
            List of KnowledgeGap objects
        """
        gap_ids = self.gaps_by_type.get(gap_type, [])
        return [self.gaps[gid] for gid in gap_ids if gid in self.gaps]
    
    def get_gaps_by_concept(self, concept_id: str) -> List[KnowledgeGap]:
        """
        Get all gaps related to a concept.
        
        Args:
            concept_id: The ID of the concept
            
        Returns:
            List of KnowledgeGap objects
        """
        gap_ids = self.gaps_by_concept.get(concept_id, [])
        return [self.gaps[gid] for gid in gap_ids if gid in self.gaps]
    
    def link_gap_to_concept(self, gap_id: str, concept_id: str) -> bool:
        """
        Link a knowledge gap to a concept.
        
        Args:
            gap_id: The ID of the gap
            concept_id: The ID of the concept
            
        Returns:
            True if successful, False otherwise
        """
        gap = self.gaps.get(gap_id)
        if not gap:
            return False
        
        if concept_id not in gap.related_concepts:
            gap.related_concepts.append(concept_id)
        
        # Index by concept
        if concept_id not in self.gaps_by_concept:
            self.gaps_by_concept[concept_id] = []
        if gap_id not in self.gaps_by_concept[concept_id]:
            self.gaps_by_concept[concept_id].append(gap_id)
        
        return True
    
    def add_investigation_method(self, gap_id: str, method: str) -> bool:
        """
        Add an investigation method to a gap.
        
        Args:
            gap_id: The ID of the gap
            method: The investigation method
            
        Returns:
            True if successful, False otherwise
        """
        gap = self.gaps.get(gap_id)
        if not gap:
            return False
        
        if method not in gap.investigation_methods:
            gap.investigation_methods.append(method)
        
        return True
    
    def start_investigation(self, gap_id: str) -> bool:
        """
        Start investigating a knowledge gap.
        
        Args:
            gap_id: The ID of the gap
            
        Returns:
            True if successful, False otherwise
        """
        gap = self.gaps.get(gap_id)
        if not gap:
            return False
        
        gap.investigation_status = "investigating"
        gap.investigation_started = datetime.utcnow()
        
        self.logger.info(f"Started investigation of gap {gap_id}")
        return True
    
    def generate_curiosity_query(self, gap_id: str, question: str,
                                keywords: Optional[List[str]] = None) -> CuriosityQuery:
        """
        Generate a curiosity query for a knowledge gap.
        
        Args:
            gap_id: The ID of the gap
            question: The question to explore
            keywords: Optional search keywords
            
        Returns:
            The generated CuriosityQuery
        """
        query = CuriosityQuery(
            gap_id=gap_id,
            question=question,
            search_keywords=keywords or []
        )
        
        self.queries[query.query_id] = query
        
        self.logger.info(f"Generated curiosity query {query.query_id}: {question}")
        return query
    
    def execute_query(self, query_id: str) -> Dict[str, Any]:
        """
        Execute a curiosity query.
        
        Args:
            query_id: The ID of the query
            
        Returns:
            Query execution results
        """
        query = self.queries.get(query_id)
        if not query:
            return {}
        
        query.executed_at = datetime.utcnow()
        
        # Simulate query execution
        results = self._search_knowledge_base(query.question, query.search_keywords)
        query.results = results
        
        # Extract insights
        query.insights_gained = self._extract_insights(results)
        
        # Update gap status if resolved
        gap = self.gaps.get(query.gap_id)
        if gap and query.insights_gained:
            gap.resolution_evidence.extend(results)
            if len(query.insights_gained) > 0:
                gap.investigation_status = "resolved"
                gap.resolved_at = datetime.utcnow()
        
        self.logger.info(f"Executed curiosity query {query_id}, gained {len(query.insights_gained)} insights")
        return {
            'query_id': query_id,
            'results_count': len(results),
            'insights': query.insights_gained
        }
    
    def _search_knowledge_base(self, question: str, keywords: List[str]) -> List[Dict[str, Any]]:
        """Search the knowledge base for relevant information."""
        # Simulate knowledge base search
        results = [
            {
                'source': 'Knowledge Base Entry 1',
                'relevance': 0.85,
                'content': f'Information about {question}'
            },
            {
                'source': 'Knowledge Base Entry 2',
                'relevance': 0.72,
                'content': f'Related information about {keywords[0] if keywords else "topic"}'
            }
        ]
        
        return results
    
    def _extract_insights(self, results: List[Dict[str, Any]]) -> List[str]:
        """Extract insights from search results."""
        insights = []
        
        for result in results:
            if result.get('relevance', 0) > 0.7:
                insights.append(f"Insight: {result.get('content', 'Information found')}")
        
        return insights
    
    def get_priority_gaps(self, limit: int = 10) -> List[KnowledgeGap]:
        """
        Get the highest priority knowledge gaps.
        
        Args:
            limit: Maximum number of gaps to return
            
        Returns:
            List of KnowledgeGap objects sorted by priority
        """
        gaps = list(self.gaps.values())
        
        # Sort by priority (descending)
        gaps.sort(key=lambda g: g.priority, reverse=True)
        
        return gaps[:limit]
    
    def resolve_gap(self, gap_id: str, resolution: str) -> bool:
        """
        Mark a knowledge gap as resolved.
        
        Args:
            gap_id: The ID of the gap
            resolution: Description of the resolution
            
        Returns:
            True if successful, False otherwise
        """
        gap = self.gaps.get(gap_id)
        if not gap:
            return False
        
        gap.investigation_status = "resolved"
        gap.resolved_at = datetime.utcnow()
        gap.proposed_solutions.append(resolution)
        
        self.logger.info(f"Resolved knowledge gap {gap_id}")
        return True
    
    def get_curiosity_statistics(self) -> Dict[str, Any]:
        """
        Get statistics about knowledge gaps and curiosity.
        
        Returns:
            Dictionary containing curiosity statistics
        """
        stats = {
            'total_gaps': len(self.gaps),
            'gaps_by_type': {},
            'gaps_by_status': {},
            'average_priority': 0.0,
            'average_impact': 0.0,
            'total_queries': len(self.queries),
            'queries_executed': 0
        }
        
        if not self.gaps:
            return stats
        
        # Count by type
        for gap_type in self.gaps_by_type:
            stats['gaps_by_type'][gap_type] = len(self.gaps_by_type[gap_type])
        
        # Count by status
        for gap in self.gaps.values():
            status = gap.investigation_status
            if status not in stats['gaps_by_status']:
                stats['gaps_by_status'][status] = 0
            stats['gaps_by_status'][status] += 1
        
        # Calculate averages
        priorities = [g.priority for g in self.gaps.values()]
        impacts = [g.potential_impact for g in self.gaps.values()]
        
        stats['average_priority'] = sum(priorities) / len(priorities) if priorities else 0.0
        stats['average_impact'] = sum(impacts) / len(impacts) if impacts else 0.0
        stats['queries_executed'] = sum(1 for q in self.queries.values() if q.executed_at)
        
        return stats
    
    def export_gaps(self, gap_ids: Optional[List[str]] = None) -> str:
        """
        Export knowledge gaps as JSON.
        
        Args:
            gap_ids: Optional list of specific gap IDs to export
            
        Returns:
            JSON string containing the gaps
        """
        if gap_ids:
            gaps = [self.gaps[gid] for gid in gap_ids if gid in self.gaps]
        else:
            gaps = list(self.gaps.values())
        
        return json.dumps([g.to_dict() for g in gaps], indent=2, default=str)
